insert into programming_language (name, runnable) values ('C', true);
insert into programming_language (name, runnable) values ('C++', true);
insert into programming_language (name, runnable) values ('Python', true);
insert into programming_language (name, runnable) values ('Go', true);
insert into programming_language (name, runnable) values ('Swift', true);
insert into programming_language (name, runnable) values ('Rust', true);
insert into programming_language (name, runnable) values ('PHP', true);
insert into programming_language (name, runnable) values ('C# (.Net Core)', true);
insert into programming_language (name, runnable) values ('Markdown', true);
insert into programming_language (name, runnable) values ('Ruby', true);
insert into programming_language (name, runnable) values ('Java', true);

insert into programming_language (name, runnable) values ('R', false);
insert into programming_language (name, runnable) values ('Bash', false);
insert into programming_language (name, runnable) values ('Coffee Script', false);
insert into programming_language (name, runnable) values ('HTML', false);
insert into programming_language (name, runnable) values ('CSS', false);
insert into programming_language (name, runnable) values ('JavaScript', false);
insert into programming_language (name, runnable) values ('F#', false);
insert into programming_language (name, runnable) values ('JSON', false);
insert into programming_language (name, runnable) values ('XML', false);
insert into programming_language (name, runnable) values ('SQL', false);
insert into programming_language (name, runnable) values ('Objective-C', false);
insert into programming_language (name, runnable) values ('MatLab', false);
insert into programming_language (name, runnable) values ('Perl', false);
insert into programming_language (name, runnable) values ('TypeScript', false);
insert into programming_language (name, runnable) values ('YAML', false);
insert into programming_language (name, runnable) values ('PL/SQL', false);
insert into programming_language (name, runnable) values ('GraphQL', false);
insert into programming_language (name, runnable) values ('Groovy', false);
insert into programming_language (name, runnable) values ('Kotlin', false);
insert into programming_language (name, runnable) values ('WebAssembly', false);