FROM debian:buster-slim

EXPOSE 80 443

RUN mkdir -p /app/data && apt-get update && apt-get install -y ca-certificates && update-ca-certificates
VOLUME [ "/app/data" ]

WORKDIR /app/cmd/server
COPY ./docker/wait-for-it.sh  wait-for-it.sh
RUN chmod +x wait-for-it.sh

COPY ./cmd/server/server ./

CMD ["./server"]